name: pytest
on: push

jobs:
        
  pytest:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v3
      - run: |
          pip install pytest
          pytest s23project/pkg/test.py
